language: php
php:
  - '7.2'
install:
  - composer install --no-dev
script:
  - composer check
before_deploy:
  - zip -r formserver.zip .
deploy:
  provider: releases
  api_key:
    secure: DCgsbefqIfIE9yGr5TRLO6VfmBRzXmmv8mvVakj2GDt0saxAhFf2duQELRFZoyFF2LUmev3wIIw/nPlff8MmdYi1/iNNNWmv0X7nUHnjjpIRdk0lT64qa7eWExZ7W2/h76cyNHzhFOAQdJ73K6sIdkMXoW3OawSI1G/S1kCGek9Q29163p5s54F10aja7fpx+F7sTF9YGU3WEepqj+31hYiuFtwgE5SdC3zR/r/IZTGKuHRoKDMw1hyCuTlrrWGvnSyvY0o+0aKhJjbcxDlmH4QWCW102p7bEZWBD64AsEWrBhg/OZhIOCucDazTAPOsmNHTW99p5HI+UNH3Zq2wNW6EEEF05rnN3QCezyomct0h7ZJUuEP6uRpfpMl4s8mKqXtM6IRjUWdkrcPsUymew47gl3bJiRzE6njNc099OyJmJeDMaaBMrweHCYg9KGFxJV4yYfifjX2xml8FOX0pRI+jGv3kjZWcgF8tnko2tAMkmr1miyebnX2itYxfGdK522THzqf0Tax//y0Z3fDTbR3G4ccZS37nbv335SI7JURtqkvKx5reCd9CO6jM1xosqwlhd95GEWD9evqMUQbb190A5qkuMIi1czbIAEzCYVifWDNa7v/QNuVKBk6uJh2ItRQfQfHb4TZDVwDl00aqjjMGzItkt8nye9eqDrKwFmY=
  file: formserver.zip
  skip_cleanup: true
  on:
    repo: cosmocode/formserver
    branch: master
    php: '7.2'
    tags: true
